#!/usr/bin/env python
#
# Copyright (c) 2017 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
# Copyright (c) 2019 Intel Corporation
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

from __future__ import print_function

import rospy
import sys
import glob
import os
import random

# ==============================================================================
# -- find carla module ---------------------------------------------------------
# ==============================================================================
try:
    sys.path.append(glob.glob('**/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
except IndexError:
    pass

import carla

# ==============================================================================
# -- GnssSensor ----------------------------------------------------------------
# ==============================================================================

class GnssSensor(object):
    def __init__(self, parent_actor):
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.other.gnss')
        self.sensor = world.spawn_actor(bp, carla.Transform(carla.Location(x=1.0, z=2.8)), attach_to=parent_actor)

    def __del__(self):
        self.sensor.destroy()

# ==============================================================================
# -- LidarSensor ---------------------------------------------------------------
# ==============================================================================

class LidarSensor(object):
    def __init__(self, parent_actor):
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.lidar.ray_cast')
        bp.set_attribute('role_name', 'sensor')
        bp.set_attribute('range', '5000')
        bp.set_attribute('channels', '32')
        bp.set_attribute('points_per_second', '320000')
        bp.set_attribute('upper_fov', '2.0')
        bp.set_attribute('lower_fov', '-26.8')
        bp.set_attribute('rotation_frequency', '20')
        self.sensor = world.spawn_actor(bp, carla.Transform(carla.Location(x=0.0, z=2.4)), attach_to=parent_actor)

    def __del__(self):
        self.sensor.destroy()

# ==============================================================================
# -- FrontCameraSensor ---------------------------------------------------------
# ==============================================================================

class FrontCamera(object):
    def __init__(self, parent_actor):
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.camera.rgb')
        bp.set_attribute('role_name', 'front')
        self.sensor = world.spawn_actor(bp, carla.Transform(carla.Location(x=2.0, z=2.0)), attach_to=parent_actor)

    def __del__(self):
        self.sensor.destroy()

# ==============================================================================
# -- CameraSensor for Visualization --------------------------------------------
# ==============================================================================

class ViewCamera(object):
    def __init__(self, parent_actor):
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.camera.rgb')
        bp.set_attribute('role_name', 'viewFromBehind')
        bp.set_attribute('image_size_x', '800')
        bp.set_attribute('image_size_y', '600')
        self.sensor = world.spawn_actor(bp, carla.Transform(carla.Location(x=-5.5, z=2.8), carla.Rotation(pitch=-15)), attach_to=parent_actor)

    def __del__(self):
        self.sensor.destroy()

# ==============================================================================
# -- CollisionSensor -----------------------------------------------------------
# ==============================================================================

class CollisionSensor(object):
    def __init__(self, parent_actor):
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.other.collision')
        self.sensor = world.spawn_actor(bp, carla.Transform(), attach_to=parent_actor)

    def __del__(self):
        self.sensor.destroy()

# ==============================================================================
# -- LaneInvasionSensor --------------------------------------------------------
# ==============================================================================

class LaneInvasionSensor(object):
    def __init__(self, parent_actor):
        world = parent_actor.get_world()
        bp = world.get_blueprint_library().find('sensor.other.lane_invasion')
        self.sensor = world.spawn_actor(bp, carla.Transform(), attach_to=parent_actor)

    def __del__(self):
        self.sensor.destroy()

# ==============================================================================
# -- EgoVehicle ---------------------------------------------------------------------
# ==============================================================================

class EgoVehicle(object):
    def __init__(self, carla_world, actor_filter, actor_spawnpoint):
        self.world = carla_world
        self.player = None
        self.collision_sensor = None
        self.lane_invasion_sensor = None
        self.gnss_sensor = None
        self.lidar_sensor = None
        self.front_camera = None
        self.view_camera = None
        self.actor_filter = actor_filter
        self.actor_spawnpoint = actor_spawnpoint
        self.restart()

    def restart(self):
        # Get a random blueprint.
        blueprint = random.choice(self.world.get_blueprint_library().filter(self.actor_filter))
        blueprint.set_attribute('role_name', 'ego_vehicle')
        if blueprint.has_attribute('color'):
            color = random.choice(blueprint.get_attribute('color').recommended_values)
            blueprint.set_attribute('color', color)
        # Spawn the player.
        if self.actor_spawnpoint:
            spawn_point = carla.Transform()
            spawn_point.location.x = self.actor_spawnpoint['X']
            spawn_point.location.y = self.actor_spawnpoint['Y']
            spawn_point.location.z = self.actor_spawnpoint['Z']
            spawn_point.rotation.yaw = self.actor_spawnpoint['Yaw']
            if self.player is not None:
                self.destroy()
            while self.player is None:
                self.player = self.world.try_spawn_actor(blueprint, spawn_point)
        else:
            if self.player is not None:
                spawn_point = self.player.get_transform()
                spawn_point.location.z += 2.0
                spawn_point.rotation.roll = 0.0
                spawn_point.rotation.pitch = 0.0
                self.destroy()
                self.player = self.world.try_spawn_actor(blueprint, spawn_point)
            while self.player is None:
                spawn_points = self.world.get_map().get_spawn_points()
                spawn_point = random.choice(spawn_points) if spawn_points else carla.Transform()
                self.player = self.world.try_spawn_actor(blueprint, spawn_point)
        # Set up the sensors.
        self.collision_sensor = CollisionSensor(self.player)
        self.lane_invasion_sensor = LaneInvasionSensor(self.player)
        self.gnss_sensor = GnssSensor(self.player)
        self.lidar_sensor = LidarSensor(self.player)
        self.front_camera = FrontCamera(self.player)
        self.view_camera = ViewCamera(self.player)

    def destroy(self):
        self.player.destroy()

# ==============================================================================
# -- main() --------------------------------------------------------------------
# ==============================================================================

def main():
    rospy.init_node('carla_client')

    host = rospy.get_param('/carla/host', '127.0.0.1')
    port = rospy.get_param('/carla/port', '2000')
    vehicle_filter = rospy.get_param('/carla/client/vehicle_filter', 'vehicle.*')
    spawn_point = rospy.get_param('/carla/client/spawn_point',{})

    rospy.loginfo('listening to server %s:%s', host, port)
    rospy.loginfo('using vehicle filter: %s', vehicle_filter)
    
    if spawn_point:
        rospy.loginfo('spawning at %s', spawn_point)
    else:
        rospy.loginfo('spawning at random point')
    
    egoVehicle = None

    try:
        client = carla.Client(host, port)
        client.set_timeout(2.0)

        egoVehicle = EgoVehicle(client.get_world(), vehicle_filter, spawn_point)

        while not rospy.is_shutdown():
            rospy.sleep(1)

    finally:

        if egoVehicle is not None:
            egoVehicle.destroy()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException: pass
        
